/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["get_deck_api_projects__name__deck_get"];
        /** Put Deck */
        put: operations["put_deck_api_projects__name__deck_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/render-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Plan */
        get: operations["get_render_plan_api_projects__name__render_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project */
        post: operations["export_project_api_projects__name__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_projects__name__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/snapshots/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Snapshot */
        post: operations["restore_snapshot_api_projects__name__snapshots__snapshot_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_projects__name__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sources/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Source */
        get: operations["read_source_api_projects__name__sources__filename__get"];
        /** Write Source */
        put: operations["write_source_api_projects__name__sources__filename__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bullet */
        Bullet: {
            /** Text */
            text: string;
            /**
             * Level
             * @default 0
             * @enum {integer}
             */
            level: 0 | 1;
        };
        /** BulletBoxSlots */
        BulletBoxSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "bullet_box";
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["Bullet"][];
            /** Conclusion */
            conclusion: string;
            /**
             * Footnote
             * @default
             */
            footnote: string;
        };
        /** CapacityWarning */
        CapacityWarning: {
            /** Chapter Id */
            chapter_id: string;
            /** Slot */
            slot: string;
            /** Message */
            message: string;
            /** Needed Pt */
            needed_pt: number;
            /** Available Pt */
            available_pt: number;
        };
        /** Card */
        Card: {
            /** Heading */
            heading: string;
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["Bullet"][];
        };
        /** Chapter */
        Chapter: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /**
             * Conclusion
             * @default
             */
            conclusion: string;
            /**
             * Template
             * @enum {string}
             */
            template: "cover" | "summary" | "bullet_box" | "table" | "compare2" | "divider";
            /**
             * Source Refs
             * @default []
             */
            source_refs: string[];
        };
        /** CompareSlots */
        CompareSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "compare2";
            left: components["schemas"]["Card"];
            right: components["schemas"]["Card"];
            /** Conclusion */
            conclusion: string;
        };
        /** CoverSlots */
        CoverSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "cover";
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Date
             * @default
             */
            date: string;
            /**
             * Audience
             * @default
             */
            audience: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** Deck */
        Deck: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            meta: components["schemas"]["DeckMeta"];
            /**
             * @default {
             *       "chapters": []
             *     }
             */
            structure: components["schemas"]["Structure"];
            /**
             * Slides
             * @default []
             */
            slides: components["schemas"]["Slide"][];
        };
        /** DeckMeta */
        DeckMeta: {
            /** Title */
            title: string;
            /**
             * Report Type
             * @default research
             * @enum {string}
             */
            report_type: "research" | "approval" | "strategy";
            /**
             * Audience
             * @default
             */
            audience: string;
            /**
             * Preset Overrides
             * @default {}
             */
            preset_overrides: {
                [key: string]: unknown;
            };
        };
        /** DividerSlots */
        DividerSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "divider";
            /**
             * Section No
             * @default
             */
            section_no: string;
            /** Section Title */
            section_title: string;
        };
        /** ExportResult */
        ExportResult: {
            /** Path */
            path: string;
        };
        /** Frame */
        Frame: {
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /** Fill */
            fill?: string | null;
            /** Border */
            border?: string | null;
            /**
             * Paras
             * @default []
             */
            paras: components["schemas"]["Para"][];
            table?: components["schemas"]["TablePlan"] | null;
            /**
             * Valign
             * @default top
             */
            valign: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Para */
        Para: {
            /** Text */
            text: string;
            /**
             * Level
             * @default 0
             */
            level: number;
            /** Font Pt */
            font_pt: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Color
             * @default 202020
             */
            color: string;
            /**
             * Align
             * @default left
             * @enum {string}
             */
            align: "left" | "center" | "right";
            /**
             * Bullet
             * @default false
             */
            bullet: boolean;
        };
        /** ProjectInfo */
        ProjectInfo: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** RenderPlan */
        RenderPlan: {
            /** Page Width Pt */
            page_width_pt: number;
            /** Page Height Pt */
            page_height_pt: number;
            style: components["schemas"]["RenderStyle"];
            /** Slides */
            slides: components["schemas"]["SlidePlan"][];
        };
        /**
         * RenderStyle
         * @description 라이터와 미리보기가 소비하는 시각 스타일. 프리셋에서 계산되어 렌더 계획에 내장된다.
         *
         *     렌더 계획은 이 블록 덕에 자기완결적이다: 소비자는 프리셋을 다시 해석하지 않는다.
         */
        RenderStyle: {
            /** Korean Font */
            korean_font: string;
            /** Latin Font */
            latin_font: string;
            /** Text Color */
            text_color: string;
            /** Box Padding Pt */
            box_padding_pt: number;
            /** Line Spacing */
            line_spacing: number;
            /** Bullet Indent Pt */
            bullet_indent_pt: number;
            /** Bullet Gap Pt */
            bullet_gap_pt: number;
            /** Table Cell Pad X Pt */
            table_cell_pad_x_pt: number;
            /** Table Cell Pad Y Pt */
            table_cell_pad_y_pt: number;
            /** Border Width Pt */
            border_width_pt: number;
            /** Bullet Char */
            bullet_char: string;
            /** Bullet Font */
            bullet_font: string;
        };
        /** Slide */
        Slide: {
            /** Chapter Id */
            chapter_id: string;
            /** Slots */
            slots: components["schemas"]["CoverSlots"] | components["schemas"]["SummarySlots"] | components["schemas"]["BulletBoxSlots"] | components["schemas"]["TableSlots"] | components["schemas"]["CompareSlots"] | components["schemas"]["DividerSlots"];
        };
        /** SlidePlan */
        SlidePlan: {
            /** Chapter Id */
            chapter_id: string;
            /** Template */
            template: string;
            /** Frames */
            frames: components["schemas"]["Frame"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["CapacityWarning"][];
        };
        /** SnapshotInfo */
        SnapshotInfo: {
            /** Id */
            id: string;
            /** Saved At */
            saved_at: string;
        };
        /** SourceText */
        SourceText: {
            /** Text */
            text: string;
        };
        /** Structure */
        Structure: {
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["Chapter"][];
        };
        /** SummarySlots */
        SummarySlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "summary";
            /** Conclusion */
            conclusion: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["Bullet"][];
        };
        /** TablePlan */
        TablePlan: {
            /** Col Widths Pt */
            col_widths_pt: number[];
            /** Header */
            header: string[];
            /** Rows */
            rows: string[][];
            /** Font Pt */
            font_pt: number;
            /** Header Fill */
            header_fill: string;
            /** Row Heights Pt */
            row_heights_pt: number[];
        };
        /** TableSlots */
        TableSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "table";
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
            /**
             * Footnote
             * @default
             */
            footnote: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deck_api_projects__name__deck_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_deck_api_projects__name__deck_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_plan_api_projects__name__render_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_projects__name__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_projects__name__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_snapshot_api_projects__name__snapshots__snapshot_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_projects__name__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_projects__name__sources__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_source_api_projects__name__sources__filename__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
