/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/preset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preset */
        get: operations["get_preset_api_preset_get"];
        /** Put Preset */
        put: operations["put_preset_api_preset_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deck */
        get: operations["get_deck_api_projects__name__deck_get"];
        /** Put Deck */
        put: operations["put_deck_api_projects__name__deck_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Snapshots */
        get: operations["list_snapshots_api_projects__name__snapshots_get"];
        put?: never;
        /** Create Snapshot */
        post: operations["create_snapshot_api_projects__name__snapshots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/render-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Render Plan */
        get: operations["get_render_plan_api_projects__name__render_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/render-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Measure Deck
         * @description 저장 없이 실측만 한다: 편집 중 미리보기와 분량 경고의 공급원 (단계 4 결정 2).
         */
        post: operations["measure_deck_api_render_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Project */
        post: operations["export_project_api_projects__name__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/snapshots/{snapshot_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Snapshot */
        post: operations["restore_snapshot_api_projects__name__snapshots__snapshot_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_projects__name__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sources/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Source */
        get: operations["read_source_api_projects__name__sources__filename__get"];
        /** Write Source */
        put: operations["write_source_api_projects__name__sources__filename__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/sources/{filename}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Source
         * @description 파일 본문을 원시 바이트로 받아 저장한다 (계획서 2026-09-01 태스크 2, 2026-09-04 B2로 XLSX 확장).
         *
         *     텍스트(.md/.txt/.csv)는 UTF-8로 해석해 sources/에만 저장한다. XLSX는 원본을 uploads/에
         *     그대로 보존하고, openpyxl로 추출한 UTF-8 텍스트를 sources/<원본 파일명>.md 로 저장한다
         *     (설계서 3.1, 가정 1). 멀티파트를 쓰지 않는 이유: 파일 1개씩만 받으므로 원시 본문이면
         *     충분하고, 파싱 의존성이 필요 없다. 표식 헤더 검사는 A2에서 공통 미들웨어로 옮겨 여기서는
         *     하지 않는다.
         */
        post: operations["upload_source_api_projects__name__sources__filename__upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/generate/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Structure */
        post: operations["generate_structure_api_projects__name__generate_structure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/generate/chapter/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Chapter */
        post: operations["generate_chapter_api_projects__name__generate_chapter__chapter_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{name}/generate/chapter/{chapter_id}/condense": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Condense Chapter */
        post: operations["condense_chapter_api_projects__name__generate_chapter__chapter_id__condense_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppStatus */
        AppStatus: {
            /**
             * Provider
             * @enum {string}
             */
            provider: "subscription" | "none";
            login: components["schemas"]["LoginStatus"];
            /** Model */
            model?: string | null;
            /** Last Generation At */
            last_generation_at?: string | null;
            /**
             * Checked At
             * @description 로그인 상태를 마지막으로 확인한 시각 (최대 60초 전 값일 수 있다)
             */
            checked_at: string;
        };
        /** Bullet */
        Bullet: {
            /** Text */
            text: string;
            /**
             * Level
             * @default 0
             * @enum {integer}
             */
            level: 0 | 1;
        };
        /** BulletBoxSlots */
        BulletBoxSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "bullet_box";
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["Bullet"][];
            /** Conclusion */
            conclusion: string;
            /**
             * Footnote
             * @default
             */
            footnote: string;
        };
        /**
         * BulletMarker
         * @description 불릿 목록 표식. 문자와 표식 전용 폰트 (승격 전에는 라이터의 리터럴이었다).
         */
        BulletMarker: {
            /**
             * Char
             * @default •
             */
            char: string;
            /**
             * Font
             * @default Arial
             */
            font: string;
        };
        /** CapacityWarning */
        CapacityWarning: {
            /** Chapter Id */
            chapter_id: string;
            /** Slot */
            slot: string;
            /** Message */
            message: string;
            /** Needed Pt */
            needed_pt: number;
            /** Available Pt */
            available_pt: number;
        };
        /** Card */
        Card: {
            /** Heading */
            heading: string;
            /**
             * Bullets
             * @default []
             */
            bullets: components["schemas"]["Bullet"][];
        };
        /** Chapter */
        Chapter: {
            /** Id */
            id: string;
            /** Topic */
            topic: string;
            /**
             * Conclusion
             * @default
             */
            conclusion: string;
            /**
             * Template
             * @enum {string}
             */
            template: "cover" | "summary" | "bullet_box" | "table" | "compare2" | "divider";
            /**
             * Source Refs
             * @default []
             */
            source_refs: string[];
        };
        /** ChapterResult */
        ChapterResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "format_error";
            /** Slots */
            slots?: (components["schemas"]["CoverSlots"] | components["schemas"]["SummarySlots"] | components["schemas"]["BulletBoxSlots"] | components["schemas"]["TableSlots"] | components["schemas"]["CompareSlots"] | components["schemas"]["DividerSlots"]) | null;
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["CapacityWarning"][];
            /**
             * Unverified Numbers
             * @default []
             */
            unverified_numbers: string[];
            /**
             * Format Retried
             * @default false
             */
            format_retried: boolean;
            /**
             * Condensed
             * @default false
             */
            condensed: boolean;
        };
        /**
         * Colors
         * @description 색상은 알파 없는 6자리 16진수 문자열.
         */
        Colors: {
            /**
             * Text
             * @default 202020
             */
            text: string;
            /**
             * Accent
             * @default 1F4E79
             */
            accent: string;
            /**
             * Box Fill
             * @default EEF3F9
             */
            box_fill: string;
            /**
             * Table Header Fill
             * @default F2F2F2
             */
            table_header_fill: string;
            /**
             * Border
             * @default D0D7E2
             */
            border: string;
            /**
             * Background
             * @default FFFFFF
             */
            background: string;
        };
        /** CompareSlots */
        CompareSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "compare2";
            left: components["schemas"]["Card"];
            right: components["schemas"]["Card"];
            /** Conclusion */
            conclusion: string;
        };
        /** CondenseChapterRequest */
        CondenseChapterRequest: {
            /** Slots */
            slots: components["schemas"]["CoverSlots"] | components["schemas"]["SummarySlots"] | components["schemas"]["BulletBoxSlots"] | components["schemas"]["TableSlots"] | components["schemas"]["CompareSlots"] | components["schemas"]["DividerSlots"];
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /**
         * CoverSlots
         * @description 표지 슬롯. 보고자는 슬롯이 아니라 메타(DeckMeta.presenter)에서 그리고, 피보고자는 문서에 적지 않는다
         *     (2026-09-01 파일럿 관찰 6: 종전 audience 필드 제거. 옛 deck.json의 audience 키는 읽을 때 무시된다).
         */
        CoverSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "cover";
            /** Title */
            title: string;
            /**
             * Subtitle
             * @default
             */
            subtitle: string;
            /**
             * Date
             * @default
             */
            date: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** Deck */
        Deck: {
            /**
             * Schema Version
             * @default 1
             */
            schema_version: number;
            meta: components["schemas"]["DeckMeta"];
            /**
             * @default {
             *       "chapters": []
             *     }
             */
            structure: components["schemas"]["Structure"];
            /**
             * Slides
             * @default []
             */
            slides: components["schemas"]["Slide"][];
        };
        /** DeckMeta */
        DeckMeta: {
            /** Title */
            title: string;
            /**
             * Report Type
             * @default research
             * @enum {string}
             */
            report_type: "research" | "approval" | "strategy";
            /**
             * Audience
             * @default
             */
            audience: string;
            /**
             * Presenter
             * @default
             */
            presenter: string;
            /**
             * Preset Overrides
             * @default {}
             */
            preset_overrides: {
                [key: string]: unknown;
            };
        };
        /** DividerSlots */
        DividerSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "divider";
            /**
             * Section No
             * @default
             */
            section_no: string;
            /** Section Title */
            section_title: string;
        };
        /** ExportResult */
        ExportResult: {
            /** Path */
            path: string;
        };
        /** FontRoles */
        FontRoles: {
            /**
             * Cover Title Pt
             * @default 28
             */
            cover_title_pt: number;
            /**
             * Section Title Pt
             * @default 24
             */
            section_title_pt: number;
            /**
             * Title Pt
             * @default 20
             */
            title_pt: number;
            /**
             * Subtitle Pt
             * @default 14
             */
            subtitle_pt: number;
            /**
             * Body Pt
             * @default 12
             */
            body_pt: number;
            /**
             * Box Pt
             * @default 12
             */
            box_pt: number;
            /**
             * Table Pt
             * @default 12
             */
            table_pt: number;
            /**
             * Footnote Pt
             * @default 9
             */
            footnote_pt: number;
            /**
             * Page Number Pt
             * @default 9
             */
            page_number_pt: number;
        };
        /** Fonts */
        Fonts: {
            /**
             * Korean
             * @default Noto Sans KR
             */
            korean: string;
            /**
             * Latin
             * @default Noto Sans KR
             */
            latin: string;
        };
        /** Frame */
        Frame: {
            /** Name */
            name: string;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** W */
            w: number;
            /** H */
            h: number;
            /** Fill */
            fill?: string | null;
            /** Border */
            border?: string | null;
            /**
             * Paras
             * @default []
             */
            paras: components["schemas"]["Para"][];
            table?: components["schemas"]["TablePlan"] | null;
            /**
             * Valign
             * @default top
             * @enum {string}
             */
            valign: "top" | "middle";
        };
        /** GenerateChapterRequest */
        GenerateChapterRequest: {
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** GenerateStructureRequest */
        GenerateStructureRequest: {
            /** Target Chapters */
            target_chapters?: number | null;
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginStatus */
        LoginStatus: {
            /** Logged In */
            logged_in?: boolean | null;
            /** Auth Method */
            auth_method?: string | null;
            /** Account */
            account?: string | null;
            /** Cli Version */
            cli_version?: string | null;
            /** Error */
            error?: string | null;
        };
        /** OkResponse */
        OkResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Para */
        Para: {
            /** Text */
            text: string;
            /**
             * Level
             * @default 0
             */
            level: number;
            /** Font Pt */
            font_pt: number;
            /**
             * Bold
             * @default false
             */
            bold: boolean;
            /**
             * Color
             * @default 202020
             */
            color: string;
            /**
             * Align
             * @default left
             * @enum {string}
             */
            align: "left" | "center" | "right";
            /**
             * Bullet
             * @default false
             */
            bullet: boolean;
            /**
             * Lines
             * @default []
             */
            lines: string[];
        };
        /** Preset */
        Preset: {
            /**
             * @default {
             *       "korean": "Noto Sans KR",
             *       "latin": "Noto Sans KR"
             *     }
             */
            fonts: components["schemas"]["Fonts"];
            /**
             * @default {
             *       "cover_title_pt": 28,
             *       "section_title_pt": 24,
             *       "title_pt": 20,
             *       "subtitle_pt": 14,
             *       "body_pt": 12,
             *       "box_pt": 12,
             *       "table_pt": 12,
             *       "footnote_pt": 9,
             *       "page_number_pt": 9
             *     }
             */
            font_roles: components["schemas"]["FontRoles"];
            /**
             * @default {
             *       "text": "202020",
             *       "accent": "1F4E79",
             *       "box_fill": "EEF3F9",
             *       "table_header_fill": "F2F2F2",
             *       "border": "D0D7E2",
             *       "background": "FFFFFF"
             *     }
             */
            colors: components["schemas"]["Colors"];
            /**
             * @default {
             *       "margin_left": 50,
             *       "margin_right": 50,
             *       "margin_top": 36,
             *       "margin_bottom": 34,
             *       "title_height": 40,
             *       "title_gap": 16,
             *       "footnote_height": 24,
             *       "footnote_gap": 8,
             *       "box_height": 56,
             *       "box_gap": 8,
             *       "box_padding": 10,
             *       "summary_box_gap": 12,
             *       "line_spacing": 1.4,
             *       "bullet_gap": 6,
             *       "bullet_indent": 18,
             *       "card_gap": 20,
             *       "card_heading_height": 24,
             *       "card_heading_gap": 8,
             *       "cover_indent": 30,
             *       "table_min_col_width": 60,
             *       "table_cell_pad_x": 6,
             *       "table_cell_pad_y": 3,
             *       "page_number_width": 60,
             *       "page_number_height": 16,
             *       "page_number_bottom": 28,
             *       "safety_ratio": 0.97,
             *       "border_width_pt": 0.75
             *     }
             */
            spacing: components["schemas"]["Spacing"];
            /**
             * @default {
             *       "char": "•",
             *       "font": "Arial"
             *     }
             */
            bullet_marker: components["schemas"]["BulletMarker"];
            /**
             * Page Width Pt
             * @default 960
             */
            page_width_pt: number;
            /**
             * Page Height Pt
             * @default 540
             */
            page_height_pt: number;
            /**
             * Language
             * @default ko-KR
             */
            language: string;
        };
        /** ProjectInfo */
        ProjectInfo: {
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /**
             * Status
             * @default ok
             * @enum {string}
             */
            status: "ok" | "needs_recovery";
        };
        /** RenderPlan */
        RenderPlan: {
            /** Page Width Pt */
            page_width_pt: number;
            /** Page Height Pt */
            page_height_pt: number;
            style: components["schemas"]["RenderStyle"];
            /** Slides */
            slides: components["schemas"]["SlidePlan"][];
        };
        /**
         * RenderStyle
         * @description 라이터와 미리보기가 소비하는 시각 스타일. 프리셋에서 계산되어 렌더 계획에 내장된다.
         *
         *     렌더 계획은 이 블록 덕에 자기완결적이다: 소비자는 프리셋을 다시 해석하지 않는다.
         */
        RenderStyle: {
            /** Korean Font */
            korean_font: string;
            /** Latin Font */
            latin_font: string;
            /** Text Color */
            text_color: string;
            /** Box Padding Pt */
            box_padding_pt: number;
            /** Line Spacing */
            line_spacing: number;
            /** Bullet Indent Pt */
            bullet_indent_pt: number;
            /** Bullet Gap Pt */
            bullet_gap_pt: number;
            /** Table Cell Pad X Pt */
            table_cell_pad_x_pt: number;
            /** Table Cell Pad Y Pt */
            table_cell_pad_y_pt: number;
            /** Border Width Pt */
            border_width_pt: number;
            /** Bullet Char */
            bullet_char: string;
            /** Bullet Font */
            bullet_font: string;
        };
        /** Slide */
        Slide: {
            /** Chapter Id */
            chapter_id: string;
            /** Slots */
            slots: components["schemas"]["CoverSlots"] | components["schemas"]["SummarySlots"] | components["schemas"]["BulletBoxSlots"] | components["schemas"]["TableSlots"] | components["schemas"]["CompareSlots"] | components["schemas"]["DividerSlots"];
        };
        /** SlidePlan */
        SlidePlan: {
            /** Chapter Id */
            chapter_id: string;
            /** Template */
            template: string;
            /** Frames */
            frames: components["schemas"]["Frame"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["CapacityWarning"][];
        };
        /** SnapshotInfo */
        SnapshotInfo: {
            /** Id */
            id: string;
            /** Saved At */
            saved_at: string;
        };
        /** SourceText */
        SourceText: {
            /** Text */
            text: string;
        };
        /** Spacing */
        Spacing: {
            /**
             * Margin Left
             * @default 50
             */
            margin_left: number;
            /**
             * Margin Right
             * @default 50
             */
            margin_right: number;
            /**
             * Margin Top
             * @default 36
             */
            margin_top: number;
            /**
             * Margin Bottom
             * @default 34
             */
            margin_bottom: number;
            /**
             * Title Height
             * @default 40
             */
            title_height: number;
            /**
             * Title Gap
             * @default 16
             */
            title_gap: number;
            /**
             * Footnote Height
             * @default 24
             */
            footnote_height: number;
            /**
             * Footnote Gap
             * @default 8
             */
            footnote_gap: number;
            /**
             * Box Height
             * @default 56
             */
            box_height: number;
            /**
             * Box Gap
             * @default 8
             */
            box_gap: number;
            /**
             * Box Padding
             * @default 10
             */
            box_padding: number;
            /**
             * Summary Box Gap
             * @default 12
             */
            summary_box_gap: number;
            /**
             * Line Spacing
             * @default 1.4
             */
            line_spacing: number;
            /**
             * Bullet Gap
             * @default 6
             */
            bullet_gap: number;
            /**
             * Bullet Indent
             * @default 18
             */
            bullet_indent: number;
            /**
             * Card Gap
             * @default 20
             */
            card_gap: number;
            /**
             * Card Heading Height
             * @default 24
             */
            card_heading_height: number;
            /**
             * Card Heading Gap
             * @default 8
             */
            card_heading_gap: number;
            /**
             * Cover Indent
             * @default 30
             */
            cover_indent: number;
            /**
             * Table Min Col Width
             * @default 60
             */
            table_min_col_width: number;
            /**
             * Table Cell Pad X
             * @default 6
             */
            table_cell_pad_x: number;
            /**
             * Table Cell Pad Y
             * @default 3
             */
            table_cell_pad_y: number;
            /**
             * Page Number Width
             * @default 60
             */
            page_number_width: number;
            /**
             * Page Number Height
             * @default 16
             */
            page_number_height: number;
            /**
             * Page Number Bottom
             * @default 28
             */
            page_number_bottom: number;
            /**
             * Safety Ratio
             * @default 0.97
             */
            safety_ratio: number;
            /**
             * Border Width Pt
             * @default 0.75
             */
            border_width_pt: number;
        };
        /** Structure */
        Structure: {
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["Chapter"][];
        };
        /** StructureResult */
        StructureResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "format_error";
            structure?: components["schemas"]["Structure"] | null;
            /**
             * Raw Text
             * @default
             */
            raw_text: string;
            /**
             * Unverified Numbers
             * @default []
             */
            unverified_numbers: string[];
            /**
             * Format Retried
             * @default false
             */
            format_retried: boolean;
        };
        /** SummarySlots */
        SummarySlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "summary";
            /** Conclusion */
            conclusion: string;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["Bullet"][];
        };
        /** TablePlan */
        TablePlan: {
            /** Col Widths Pt */
            col_widths_pt: number[];
            /** Header */
            header: string[];
            /** Rows */
            rows: string[][];
            /** Font Pt */
            font_pt: number;
            /** Header Fill */
            header_fill: string;
            /** Row Heights Pt */
            row_heights_pt: number[];
            /**
             * Header Lines
             * @default []
             */
            header_lines: string[][];
            /**
             * Cell Lines
             * @default []
             */
            cell_lines: string[][][];
        };
        /** TableSlots */
        TableSlots: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            template: "table";
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
            /**
             * Footnote
             * @default
             */
            footnote: string;
        };
        /** UploadResult */
        UploadResult: {
            /** Filename */
            filename: string;
            /** Chars */
            chars: number;
            /** Sheets */
            sheets: number | null;
            /** Cells */
            cells: number | null;
            /** Truncated */
            truncated: boolean;
            /** Notes */
            notes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_preset_api_preset_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preset"];
                };
            };
        };
    };
    put_preset_api_preset_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preset"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"][];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deck_api_projects__name__deck_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_deck_api_projects__name__deck_put: {
        parameters: {
            query?: {
                snapshot?: boolean;
            };
            header?: {
                "if-match"?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_projects__name__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_snapshot_api_projects__name__snapshots_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_render_plan_api_projects__name__render_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    measure_deck_api_render_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Deck"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_projects__name__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_snapshot_api_projects__name__snapshots__snapshot_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                "if-match"?: string | null;
            };
            path: {
                name: string;
                snapshot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_projects__name__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_source_api_projects__name__sources__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceText"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    write_source_api_projects__name__sources__filename__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_api_projects__name__sources__filename__upload_post: {
        parameters: {
            query?: {
                overwrite?: boolean;
            };
            header?: never;
            path: {
                name: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppStatus"];
                };
            };
        };
    };
    generate_structure_api_projects__name__generate_structure_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateStructureRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_chapter_api_projects__name__generate_chapter__chapter_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateChapterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    condense_chapter_api_projects__name__generate_chapter__chapter_id__condense_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CondenseChapterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
